#!/bin/sh 

#EOPSY Laboratory task 1
#Kacper Kamieniarz (293065)


COUNT=0		    # number of files renamed
SED=""		    # sed pattern
DEPTH="-maxdepth 0" # option for find command

renameFile()	    # $1 = filename 
{
PATHNAME=$(dirname $1)
case $OPTION in
	u) FILENAME=`echo $(basename $1) | tr a-z A-Z`
	   NEW="${PATHNAME}/${FILENAME}";;
       	l) FILENAME=`echo $(basename $1) | tr A-Z a-z`
 	   NEW="${PATHNAME}/${FILENAME}";;
         
	s) FILENAME=`echo $(basename $1) | sed -s  "$SED"` 2>/dev/null # turns off stderr for this command
           if test $? != 0; then
		 echo "Wrong sed pattern!"
		 return 1
	   fi
	   NEW="${PATHNAME}/${FILENAME}";;
esac
           if ! test -e "$NEW"; then
		 mv "$1" "$NEW"
		 if test $? = 0; then
		 COUNT=$((COUNT+1))
		 fi
	   elif test "$FILENAME" != $(basename $1); then
	 	 echo "Couldn't modify $(basename $1) in $PATHNAME becasue $FILENAME already exists!"
	   fi
}

displayHelp()
{
echo "\tmodify [-r] [-l | -u] <dir/file names...>"
echo "\tmodify [-r] <sed pattern> <dir/file names...>"
echo "\n\t[-r] - with this option files are renamed recursively"
echo "\t[-l] - lowercasing the name\n\t[-u] - uppercasing the name"
echo "\t<sed pattern> - apply sed command to the filenames"
}
if [ $# -lt 1 ]; then
	echo "No arguments! To see help, use: modify -h" 
	exit 1
fi


case "$1" in
	-r) DEPTH="-mindepth 1" shift;;
	-h) displayHelp; exit 0; shift;;
esac	

case "$1" in
	-u) OPTION=u;;
	-l) OPTION=l;;
     	 *) SED=$1 OPTION=s;;
esac

shift

if test -z "$1"; then
	echo "Not enough arguments! To see help, use: modify -h"
	exit 1
fi


while test -n "$1"
do
	if test -f "$1"; then
		renameFile "$1"
		shift
	
	elif test -d "$1"; then
		for i in `find "$1" $DEPTH -type f`; do
			renameFile "$i"
		done
		if [ -z $i ]  && [ "$DEPTH" = "-mindepth 1" ]; then
			echo "No files to rename in $1."
		elif [ -z $i ] && [ "$DEPTH" = "-maxdepth 0" ]; then
			echo "$1 is a directory."
		fi
		shift
	else
		echo "No such file or directory: $1"
		shift
	fi
done
echo "$COUNT files were renamed.\n"
